/**
 * Built-in Prompt Library & Slash Commands Catalog for LocalLLMMind
 * Single source of truth for default slash commands and prompt templates.
 * Designed & Engineered by Kapil Kumar Yadav
 */

export const DEFAULT_PROMPTS = [
  {
    id: 'refactor',
    command: '/refactor',
    title: 'Refactor & Clean Code',
    description: 'Restructure code for readability, performance, and design patterns without changing behavior.',
    category: 'Coding',
    icon: '⚡',
    template: `Please refactor the following code to improve its readability, maintainability, and performance. Ensure best practices, clean architecture, and type safety are maintained, and explain the key improvements made:\n\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
  {
    id: 'test',
    command: '/test',
    title: 'Generate Unit Tests',
    description: 'Create comprehensive unit tests covering edge cases, mocks, and error states.',
    category: 'Coding',
    icon: '🧪',
    template: `Write comprehensive unit tests for the following code. Cover normal execution, boundary conditions, edge cases, and failure scenarios. Use modern test runners (e.g. Vitest/Jest, PyTest, or Go test):\n\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
  {
    id: 'explain',
    command: '/explain',
    title: 'Explain Code / Concept',
    description: 'Break down complex logic, algorithms, or architectures into clear plain-English explanations.',
    category: 'Learning',
    icon: '💡',
    template: `Please explain the following code or technical concept step-by-step. Break it down in plain, intuitive English, highlight critical patterns, and explain how each part fits into the overall architecture:\n\n\`\`\`\n[Paste code or concept here]\n\`\`\``,
  },
  {
    id: 'security',
    command: '/security',
    title: 'Security Audit & OWASP',
    description: 'Inspect code for vulnerabilities, injection vectors, sanitization gaps, and memory leaks.',
    category: 'Security',
    icon: '🛡️',
    template: `Perform an in-depth security and vulnerability audit on the following code. Inspect for OWASP Top 10 vulnerabilities, injection flaws, sensitive data exposure, race conditions, and memory leaks. Provide concrete fixes for any issues found:\n\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
  {
    id: 'fix',
    command: '/fix',
    title: 'Diagnose & Fix Error',
    description: 'Analyze error stack traces and broken code to pinpoint the root cause and provide solutions.',
    category: 'Coding',
    icon: '🔧',
    template: `I encountered an error. Here is the error message/stack trace and the relevant code. Please diagnose the root cause and provide a corrected, working version of the code:\n\n**Error Message:**\n\`\`\`\n[Paste error here]\n\`\`\`\n\n**Relevant Code:**\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
  {
    id: 'summarize',
    command: '/summarize',
    title: 'Executive Summary',
    description: 'Condense articles, meeting notes, or long documents into actionable bullet points.',
    category: 'Writing',
    icon: '📋',
    template: `Please provide a high-level executive summary of the following text. Structure your response with:\n1. Key Takeaways (3-5 bullet points)\n2. Actionable Insights\n3. Notable Details or Decisions\n\n**Text to summarize:**\n[Paste text or document content here]`,
  },
  {
    id: 'regex',
    command: '/regex',
    title: 'Regex Generator & Explainer',
    description: 'Generate regular expressions with explanations, breakdown diagrams, and test examples.',
    category: 'Utilities',
    icon: '🔍',
    template: `Generate a robust regular expression for the following pattern requirement. Explain each group, flag, and token in detail, and provide test cases including matching strings and non-matching edge cases:\n\n**Requirement:** [Describe what you want to match/validate]`,
  },
  {
    id: 'sql',
    command: '/sql',
    title: 'SQL Query & Schema Optimizer',
    description: 'Write, analyze, or optimize complex SQL queries and recommend database indexes.',
    category: 'Database',
    icon: '🗄️',
    template: `Write or optimize a high-performance SQL query for the following requirement. Provide the query, explain the execution plan, and recommend appropriate indexes to ensure optimal query performance:\n\n**Requirement / Current Query:**\n[Describe schema and query requirement here]`,
  },
  {
    id: 'doc',
    command: '/doc',
    title: 'Generate Documentation',
    description: 'Create thorough documentation, JSDoc/Docstrings, and API endpoint specifications.',
    category: 'Coding',
    icon: '📚',
    template: `Generate comprehensive, production-grade documentation for the following code. Include parameter descriptions, return types, exceptions thrown, usage examples, and architecture notes (in JSDoc, Python Docstrings, or Markdown):\n\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
  {
    id: 'diagram',
    command: '/diagram',
    title: 'Mermaid Architecture Diagram',
    description: 'Generate interactive Mermaid flowchart, sequence, or class diagrams for visual systems.',
    category: 'Design',
    icon: '📊',
    template: `Create a clean, visually informative Mermaid.js diagram representing the following workflow, architecture, or data model. Provide the complete \`\`\`mermaid code block and a concise summary explaining the flow:\n\n**System / Architecture Description:**\n[Describe the system or flow here]`,
  },
  {
    id: 'translate',
    command: '/translate',
    title: 'Natural Translation',
    description: 'Translate text accurately into target languages preserving nuances and professional tone.',
    category: 'Writing',
    icon: '🌐',
    template: `Translate the following text into [Target Language]. Preserve the original nuances, idioms, and professional tone. Provide alternative expressions where helpful:\n\n**Text to translate:**\n[Paste text here]`,
  },
  {
    id: 'review',
    command: '/review',
    title: 'Principal Code Review',
    description: 'Conduct a thorough code review like a staff engineer: architecture, cleanliness, and edge cases.',
    category: 'Coding',
    icon: '🧐',
    template: `Please conduct a comprehensive code review of the following snippet as a Senior/Staff Software Engineer. Evaluate:\n1. Architecture & Design Patterns\n2. Potential Bugs & Edge Cases\n3. Performance & Efficiency\n4. Readability & Idiomatic Conventions\n\n\`\`\`\n[Paste code here]\n\`\`\``,
  },
];

export const PROMPT_CATEGORIES = [
  'All',
  'Coding',
  'Writing',
  'Learning',
  'Security',
  'Database',
  'Utilities',
  'Design',
  'Custom',
];
